### ISSUE TITLE
leere zeilen in einer html datei entfernen

### ISSUE THREAD

**Issue by LFF5644** [mattes2008/Open#1]
es sind viele leere zeilen in der html datei wieso?
hat das irgendeinen grund?
wenn nein bitte entfernen!
https://github.com/mattes2008/Open/blob/a4902bc14db3930c976b6664c7ba5ad5c95697c2/OpenUI/preview.html#L1-L13

**Comment by mattes2008** [comment]
Die Leerzeilen sind für mich einfach angenehmer, da ich das ordentlicher finde.

**Comment by LFF5644** [comment]
ok

**Comment by LFF5644** [comment]
https://github.com/mattes2008/Open/issues/4
