### ISSUE TITLE
ich mag keine classen!

### ISSUE THREAD

**Issue by LFF5644** [mattes2008/Open#2]
wieso classen ich verstehe diese leute nicht die egal was eine F***** classe nutzen
https://github.com/mattes2008/Open/blob/a4902bc14db3930c976b6664c7ba5ad5c95697c2/Open/open.js#L73
https://github.com/mattes2008/Open/blob/a4902bc14db3930c976b6664c7ba5ad5c95697c2/Open/open.js#L105

ps. eine normale function "tut" ihre aufgabe auch erfüllen

**Comment by mattes2008** [comment]
Die Link-Klasse ist tatsächlich eher unnötig, aber mit der AjaxCall-Klasse kann man den AjaxCall sehr einfach durchführen und das Ergebnis weiterverarbeiten.
